### ISSUE TITLE
Missing module 'browserid'

### ISSUE THREAD

**Issue by karlht** [mozilla-services/tokenserver-loadtests#1]
Copying from https://github.com/mozilla-services/tokenserver/issues/97:

```
[0] 12:29 (ttys002) kthiessen@kthiessen-16107:~ 502$ moloslave https://github.com/mozilla-services/tokenserver-loadtests smoke
Working directory is /var/folders/tr/zhjwv42949g6vnw9p1bgw73w0000gp/T/tmp7dlpypox
Cloning into '.'...
remote: Counting objects: 22, done.        
remote: Total 22 (delta 0), reused 0 (delta 0), pack-reused 22        
Unpacking objects: 100% (22/22), done.
Already using interpreter /usr/local/opt/python3/bin/python3.6
Using base prefix '/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6'
New python executable in /private/var/folders/tr/zhjwv42949g6vnw9p1bgw73w0000gp/T/tmp7dlpypox/venv/bin/python3.6
Also creating executable in /private/var/folders/tr/zhjwv42949g6vnw9p1bgw73w0000gp/T/tmp7dlpypox/venv/bin/python
Installing setuptools, pip, wheel...done.
Running: molotov -r 1 loadtest.py
**** Molotov v1.4. Happy breaking! ****
Traceback (most recent call last):
  File "/usr/local/bin/moloslave", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/molotov/slave.py", line 118, in main
    run_test(**config['molotov']['tests'][args.run])
  File "/usr/local/lib/python3.6/site-packages/molotov/slave.py", line 59, in run_test
    return run(args)
  File "/usr/local/lib/python3.6/site-packages/molotov/run.py", line 179, in run
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "loadtest.py", line 9, in <module>
ModuleNotFoundError: No module named 'browserid'
```

**Comment by rfk** [comment]
It's not obvious from the description, did you do a `make build` in this repo to pull in local dependencies, or are you running `moloslave` from a global install somewhere?  The local requirements.txt appears to include `PyBrowserID` correctly.

**Comment by tarekziade** [comment]
the requirements.txt file needs to be plugged into molotov.json. I am not sure why it's not there. 

Can you guys allow me to write into this repo? @jvehent stripped my rights in mozilla-services I cannot push changes

**Comment by karlht** [comment]
@tarek Done!

**Comment by karlht** [comment]
This is fixed by https://github.com/mozilla-services/tokenserver-loadtests/commit/c757a440d0e9daeedb49d64a0758e58b9c530a7f  -- Thanks @tarekziade!
